* Conquer

A simple yet powerful template rendering tool that follows the Unix
philosophy of doing one thing well.

** Overview

Conquer is a command-line utility that generates text files by
combining structured data (YAML/CSV) with templates.

** Features

- Supports YAML and CSV input files
- Uses Comb templates (=.comb= extension)
- Direct file updates with =-u= flag
- Directory tree processing
- Simple command-line interface

** Installation

#+begin_src bash
bbin install io.github.200ok-ch/conquer
#+end_src

** Usage

Basic syntax:
#+begin_example
conquer [-t=<template>] [-u] <file-or-directory>
#+end_example

Options:
- =-h, --help=: Show help screen
- =-t, --template=<template>=: Override the template file
- =-u, --update=: Create or update files
- =-v, --version=: Show version

*** Basic Example

#+begin_src bash
conquer -t template.html.comb greeting.yml
#+end_src

Read more about conquer in my [[x][blog post]] (soonish).

*** Troubleshooting

This error

#+begin_example
java.lang.String cannot be cast to clojure.lang.IFn
#+end_example

Is most likely an error in the template. It happens when you try to
use a function it cannot resolve.

** Use Cases

- Static website generation
- Configuration file management
- Documentation generation
- Report creation
- Data transformation
- Infrastructure as Code (e.g. Terraform/OpenTofu configurations)

** License

tbd.
